# Generated by Django 4.1.1 on 2022-09-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_alter_moto_is_published_alter_moto_time_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='moto',
            options={'verbose_name': 'Мотоцикл', 'verbose_name_plural': 'Мотоциклы'},
        ),
    ]
