# Generated by Django 4.1.1 on 2022-09-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0003_alter_cats_options_alter_moto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.cats', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время Создания'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
